### PR TITLE
Compare ZG(2) to Minka Simulations 

### LINKED ISSUE #360: compare ZG(2) to minka
to select the number of components in PCA, sklearn uses this: 
https://papers.nips.cc/paper/1853-automatic-choice-of-dimensionality-for-pca.pdf

but graspy uses this: https://www.sciencedirect.com/science/article/abs/pii/S0167947305002343

compare the two via simulations and see which is better, and if either of us should switch

### PR DESCRIPTION
**Pull request by dfrancisco1998**
fixes https://github.com/microsoft/graspologic/issues/360

### CODE REVIEW

**Comment by dfrancisco1998** [comment]
<p>Jovo has had similar thoughts, but it would be a feat of overengineering to do so. It is just because sometimes the lines are spaced too close to even legibly do this... figuring all this out would be spending time on something that is not necessarily conducive to the results. </p>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dfrancisco1998** [comment]
<p>https://github.com/neurodata/notebooks/pull/6/commits/58c2d930a4745045d443cdfd8bd9d2ac419c5c87 should fix 1 and 2</p><p> </p>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dfrancisco1998** [comment]
<p>https://github.com/neurodata/notebooks/pull/6/commits/1775766d2ff99b1d1a227f6da993b43f639a27ba </p>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dfrancisco1998** [comment]
<p>https://github.com/neurodata/notebooks/pull/6/commits/1775766d2ff99b1d1a227f6da993b43f639a27ba</p>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dfrancisco1998** [comment]
<ol><li>So this is not really a function and it is running the simulation so making a function for each individual simulation I do not think would be worthwhile in a notebook. </li><li>https://github.com/neurodata/notebooks/pull/6/commits/7621d6cf19223abb76c8dc1378e1387bd7d27e0f </li></ol>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dfrancisco1998** [comment]
<ol><li>https://github.com/neurodata/notebooks/pull/6/commits/7266f2b92988c4dcf01b9ba75aaac59c8e8e69e7 </li><li>yea unsure how to help with this. It is just a lot and that is because of the simulation settings. But it is the same analysis that is applied to the graphs before </li></ol>

---

 <a href='https://app.reviewnb.com/neurodata/notebooks/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bdpedigo** [comment]
replaced by #8 ?

**Pull request closed without merging**
